{
 "title": "Ziggo Arris Modem",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Upstream TX Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "dBmV" }
   ],
   "targets": [
    {
     "alias": "Channel $tag_channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docsIf3CmStatusUsTxPower",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "dBmV" }
   ],
   "targets": [
    {
     "alias": "Channel $tag_channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docsIfDownChannelPower",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream Freq",
   "type": "table",
   "gridPos": { "h": 17, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "Channel $tag_channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docsIfDownChannelFrequency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream Freq",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "targets": [
    {
     "alias": "Channel $tag_channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docsIfUpChannelFrequency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Signal/Noise ratio",
   "type": "graph",
   "description": "\"Signal/Noise ratio as perceived for this channel.\nAt the CM, describes the Signal/Noise of the downstream\nchannel. At the CMTS, describes the average Signal/Noise\nof the upstream channel.\"",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "SNR" }
   ],
   "targets": [
    {
     "alias": "Channel $tag_channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docsIfSigQSignalNoise",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pre Reed Solomon Errors",
   "type": "graph",
   "description": "Een Reed-Solomoncode ofwel RS-code is een foutdetectie en -correctiecode die wordt gebruikt om mogelijke transmissiefouten te detecteren en/of te corrigeren door gebruik te maken van extra, redundante informatie.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "RS" }
   ],
   "targets": [
    {
     "alias": "Channel $tag_channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docsIfSigQCorrecteds",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  }
 ]
}